export const demoJobs = [
  {
    id: 1,
    title: "Web Developer",
    description: "Develop and maintain websites and web applications.",
    location: "Remote",
    employment_type: "Full-time",
    salary: "$60,000 - $80,000",
    created_at: "2024-10-20T08:30:00Z",
  },
  {
    id: 2,
    title: "Frontend Developer",
    description:
      "Build and enhance UI components using HTML, CSS, and JavaScript.",
    location: "San Francisco, CA",
    employment_type: "Contract",
    salary: "$40/hour",
    created_at: "2024-10-20T08:31:00Z",
  },
  {
    id: 3,
    title: "Backend Developer",
    description: "Work on server-side logic and API development.",
    location: "New York, NY",
    employment_type: "Part-time",
    salary: "$50,000 - $70,000",
    created_at: "2024-10-20T08:32:00Z",
  },
  {
    id: 4,
    title: "Full Stack Developer",
    description: "Handle both frontend and backend development.",
    location: "Remote",
    employment_type: "Full-time",
    salary: "$80,000 - $100,000",
    created_at: "2024-10-20T08:33:00Z",
  },
  {
    id: 5,
    title: "Mobile App Developer",
    description:
      "Design and build mobile applications for iOS and Android platforms.",
    location: "Austin, TX",
    employment_type: "Full-time",
    salary: "$70,000 - $90,000",
    created_at: "2024-10-20T08:34:00Z",
  },
  {
    id: 6,
    title: "UI/UX Designer",
    description:
      "Create user-friendly interfaces and design experiences for web and mobile apps.",
    location: "Los Angeles, CA",
    employment_type: "Full-time",
    salary: "$65,000 - $85,000",
    created_at: "2024-10-20T08:35:00Z",
  },
  {
    id: 7,
    title: "DevOps Engineer",
    description:
      "Manage infrastructure and deploy applications in a CI/CD pipeline.",
    location: "Seattle, WA",
    employment_type: "Full-time",
    salary: "$90,000 - $110,000",
    created_at: "2024-10-20T08:36:00Z",
  },
  {
    id: 8,
    title: "Cloud Architect",
    description: "Design and manage cloud infrastructure and services.",
    location: "Remote",
    employment_type: "Full-time",
    salary: "$100,000 - $120,000",
    created_at: "2024-10-20T08:37:00Z",
  },
  {
    id: 9,
    title: "Data Scientist",
    description:
      "Analyze data to provide insights and build predictive models.",
    location: "Chicago, IL",
    employment_type: "Part-time",
    salary: "$90,000 - $110,000",
    created_at: "2024-10-20T08:38:00Z",
  },
  {
    id: 10,
    title: "Machine Learning Engineer",
    description: "Develop and deploy machine learning algorithms and models.",
    location: "Boston, MA",
    employment_type: "Full-time",
    salary: "$110,000 - $130,000",
    created_at: "2024-10-20T08:39:00Z",
  },
  {
    id: 11,
    title: "Cybersecurity Analyst",
    description:
      "Monitor and secure networks, systems, and data from cyber threats.",
    location: "Remote",
    employment_type: "Contract",
    salary: "$60,000 - $80,000",
    created_at: "2024-10-20T08:40:00Z",
  },
  {
    id: 12,
    title: "Software Engineer",
    description: "Develop, test, and maintain software applications.",
    location: "Denver, CO",
    employment_type: "Full-time",
    salary: "$85,000 - $105,000",
    created_at: "2024-10-20T08:41:00Z",
  },
  {
    id: 13,
    title: "Systems Analyst",
    description: "Analyze and improve system processes and workflows.",
    location: "Phoenix, AZ",
    employment_type: "Full-time",
    salary: "$70,000 - $90,000",
    created_at: "2024-10-20T08:42:00Z",
  },
  {
    id: 14,
    title: "Network Administrator",
    description: "Maintain and support network infrastructure.",
    location: "Dallas, TX",
    employment_type: "Part-time",
    salary: "$50,000 - $70,000",
    created_at: "2024-10-20T08:43:00Z",
  },
  {
    id: 15,
    title: "Database Administrator",
    description: "Manage, secure, and optimize database systems.",
    location: "Houston, TX",
    employment_type: "Full-time",
    salary: "$80,000 - $100,000",
    created_at: "2024-10-20T08:44:00Z",
  },
  {
    id: 16,
    title: "IT Support Specialist",
    description: "Provide technical support to users and resolve IT issues.",
    location: "Miami, FL",
    employment_type: "Full-time",
    salary: "$45,000 - $65,000",
    created_at: "2024-10-20T08:45:00Z",
  },
  {
    id: 17,
    title: "QA Engineer",
    description:
      "Test and ensure the quality of software products before release.",
    location: "Remote",
    employment_type: "Full-time",
    salary: "$65,000 - $85,000",
    created_at: "2024-10-20T08:46:00Z",
  },
  {
    id: 18,
    title: "Business Analyst",
    description: "Analyze business needs and recommend solutions.",
    location: "Philadelphia, PA",
    employment_type: "Contract",
    salary: "$70,000 - $90,000",
    created_at: "2024-10-20T08:47:00Z",
  },
  {
    id: 19,
    title: "Project Manager",
    description:
      "Plan, execute, and deliver projects on time and within budget.",
    location: "Remote",
    employment_type: "Full-time",
    salary: "$90,000 - $110,000",
    created_at: "2024-10-20T08:48:00Z",
  },
  {
    id: 20,
    title: "Product Manager",
    description: "Lead product development and manage product lifecycle.",
    location: "Atlanta, GA",
    employment_type: "Full-time",
    salary: "$100,000 - $120,000",
    created_at: "2024-10-20T08:49:00Z",
  },
  {
    id: 21,
    title: "Digital Marketing Specialist",
    description:
      "Develop and execute digital marketing campaigns to boost online presence.",
    location: "Remote",
    employment_type: "Contract",
    salary: "$55,000 - $75,000",
    created_at: "2024-10-20T08:50:00Z",
  },
  {
    id: 22,
    title: "SEO Specialist",
    description: "Optimize websites for search engines to improve rankings.",
    location: "San Diego, CA",
    employment_type: "Part-time",
    salary: "$45,000 - $65,000",
    created_at: "2024-10-20T08:51:00Z",
  },
  {
    id: 23,
    title: "Content Writer",
    description:
      "Create engaging content for websites, blogs, and social media.",
    location: "Remote",
    employment_type: "Contract",
    salary: "$30/hour",
    created_at: "2024-10-20T08:52:00Z",
  },
]
